name: CI

# Run on every push and every pull request to main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: Build (RP2350)
        runs-on: ubuntu-latest
        steps:
            # Checkout repo code to runner
            - name: Checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            # Install Rust toolchain
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                # RP2350 ARM M33 target
                targets: thumbv8m.main-none-eabihf

            # Compile firmware for RP2350 target
            - name: Build
              run: cargo build --verbose
    
    clippy:
        name: Clippy (SAST linter)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                # RP2350 ARM M33 target
                targets: thumbv8m.main-none-eabihf
                components: clippy

            - name: Run Clippy
              # Gate 1: -D warnings turn into errors, gating the pipeline to fail on a finding
              run: cargo clippy -- -D warnings

    sbom:
        name: SBOM (Syft)
        runs-on: ubuntu-latest
        steps:
            -  name: Checkout
               uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            # Generate SBOM of entire project directory
            # Syft reads Cargo.lock to inventory Rust dependencies
            - name: Genereate SBOM with Syft
              uses: anchore/sbom-action@v0
              with:
                path: .
                format: spdx-json
                output-file: sbom.spdx.json
            
            # Save SBOM as downloadable artifact from the run
            - name: Upload SBOM
              uses: actions/upload-artifact@v4
              with:
                name: sbom
                path: sbom.spdx.json

    vuln-scan:
        name: Vulnerability Scan (Grype)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            # Scan project directory for vulnerabilities
            # Grype reads Cargo.lock and checks dependency against vuln DBs
            - name: Scan for vulnerabiltities with Grype
              uses: anchore/scan-action@v7
              with:
                path: "."
                # Gate 2: Fail the build if any highs or above are found 
                fail-build: true
                severity-cutoff: high

    trivy:
        name: Trivy (vuln + secret + config scan)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            # Trivy scans for vulns, secrets, and misconfigurations
            - name: Run Trivy scan
              # Explicit SHA for new post-supply chain attack that uses the v prefix for versions
              uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
              with:
                scan-type: 'fs'
                scan-ref: '.'
                scanners: vuln,secret,misconfig,license
                # Gate 3: Fail build on high/crit findings
                severity: HIGH, CRITICAL
                exit-code: 1